development:
  adapter: postgresql
  encoding: unicode
  database: store_development
  pool: 5
  username: task_manager_std
  password:
  host: 127.0.0.1

test:
  adapter: postgresql
  encoding: unicode
  database: store_test
  pool: 5
  usernanme: task_manager_std
  password:
  host: 127.0.0.1
